spring:
  application:
    name :demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market
    username: root
    password: 9897

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true