version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: umc9th-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "umc9th"
      TZ: "Asia/Seoul"

    ports:
      - "3306:3306"

    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d

    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
